# Generated by Django 3.0.6 on 2020-05-15 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 4, 55, 4, 408337, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
