# Generated by Django 3.0.6 on 2020-05-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_filter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter',
            new_name='Sorter',
        ),
    ]
